import os, cv2, time, requests, base64, winsound, re, csv, uuid, asyncio
import numpy as np
from rapidfuzz import fuzz
from dotenv import load_dotenv
from playwright.async_api import async_playwright
import speech_recognition as sr

# 1. INITIALIZATION
load_dotenv()
API_KEY = os.getenv("SARVAM_API_KEY")
USER_DB = "pension_users.csv"

# Mock Data for demo stability
DATASET = {
    "aadhaar": "NAME: RAGHAVAN MK DOB: 01/02/1960 GENDER: MALE ACC: 99887766",
    "pension": "NAME: RAGHAVAN MK DOB: 01/03/1960 GENDER: MALE PPO: 88776655 ACC: 90887766",
}

# --- 2. VOICE ENGINES ---

def speak_native(text):
    if not text: return
    print(f"[VOICE]: {text}")
    url = "https://api.sarvam.ai/text-to-speech"
    headers = {"api-subscription-key": API_KEY, "Content-Type": "application/json"}
    payload = {"text": text, "target_language_code": "ml-IN", "speaker": "ritu", "model": "bulbul:v3"}
    try:
        res = requests.post(url, json=payload, headers=headers, timeout=8)
        if res.status_code == 200:
            with open("voice.wav", "wb") as f:
                f.write(base64.b64decode(res.json()['audios'][0]))
            winsound.PlaySound("voice.wav", winsound.SND_FILENAME)
    except Exception as e:
        print(f"TTS Error: {e}")

def listen_for_command():
    recognizer = sr.Recognizer()
    with sr.Microphone() as source:
        print("\n[LISTENING] (അടുത്തത് / വീണ്ടും / നിർത്താം)...")
        recognizer.adjust_for_ambient_noise(source, duration=0.8)
        try:
            audio = recognizer.listen(source, timeout=7)
            text = recognizer.recognize_google(audio, language='ml-IN').lower()
            print(f">> User said: {text}")
            return text
        except:
            return ""

# --- 3. CORRECTION LETTER LOGIC ---

def show_correction_letter(u_name, ppo_val, mismatches):
    # Create white background
    letter_img = np.ones((650, 800, 3), dtype=np.uint8) * 255
    
    # Header
    cv2.putText(letter_img, "CORRECTION REQUEST: PENSION-MITRA", (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (150, 0, 0), 2)
    cv2.line(letter_img, (50, 65), (750, 65), (0, 0, 0), 1)

    content = [
        f"Date: {time.strftime('%d/%m/%Y')}",
        f"To: The Bank Manager, SBI Aluva (manager.aluva@sbi.co.in)",
        f"From: {u_name}",
        "",
        f"Subject: Discrepancy Found in Pension Record (PPO: {ppo_val})",
        "",
        "Dear Sir/Madam,",
        "The following mismatches were detected during verification:",
        ""
    ]

    for error in mismatches:
        content.append(f"   [!] MISMATCH IN: {error}")

    footer = [
        "",
        "Kindly update these details to enable life certificate generation.",
        "",
        "Generated by: Pension-Mitra AI Agent",
        "",
        "Press 'S' to SAVE / ESC to Exit"
    ]
    content.extend(footer)

    y_pos = 100
    for line in content:
        # Use Red for mismatch lines, Black for others
        color = (0, 0, 255) if "[!]" in line else (0, 0, 0)
        thickness = 2 if "[!]" in line else 1
        cv2.putText(letter_img, line, (50, y_pos), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, thickness)
        y_pos += 35

    cv2.imshow("CORRECTION LETTER", letter_img)
    
    # NEW INSTRUCTION VOICE
    speak_native("കത്ത് സേവ് ചെയ്യുന്നതിനായി എസ് അമർത്തുക.")
    
    key = cv2.waitKey(0) & 0xFF
    if key in [ord('s'), ord('S')]:
        cv2.imwrite("Correction_Letter.jpg", letter_img)
        speak_native("കത്ത് വിജയകരമായി സേവ് ചെയ്തിട്ടുണ്ട്. ഇത് ബാങ്കിൽ സമർപ്പിക്കുക.")
    cv2.destroyAllWindows()

# --- 4. SESSION & SCANNING ---

def user_session_manager():
    if not os.path.exists(USER_DB):
        with open(USER_DB, "w", newline="", encoding='utf-8') as f:
            csv.writer(f).writerow(["UserID", "Name", "Phone"])
    
    speak_native("പെൻഷൻ മിത്രയിലേക്ക് സ്വാഗതം. ലോഗിൻ ചെയ്യാൻ ഒന്ന് എന്നും, രജിസ്റ്റർ ചെയ്യാൻ രണ്ട് എന്നും ടൈപ്പ് ചെയ്യുക.")
    choice = input("1. Login | 2. Register: ").strip()
    
    if choice == "2":
        speak_native("ദയവായി നിങ്ങളുടെ പേരും ഫോൺ നമ്പറും ടൈപ്പ് ചെയ്യുക.")
        name = input("Enter Name: "); phone = input("Enter Phone: ")
        u_id = f"PM-{uuid.uuid4().hex[:4].upper()}"
        with open(USER_DB, "a", newline="", encoding='utf-8') as f:
            csv.writer(f).writerow([u_id, name, phone])
        speak_native(f"രജിസ്ട്രേഷൻ വിജയിച്ചു. നിങ്ങളുടെ ഐഡി {u_id} ആണ്.")
        return u_id, name
    else:
        search_id = input("Enter User ID: ").strip().upper()
        with open(USER_DB, "r", encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                if row["UserID"] == search_id:
                    speak_native(f"വീണ്ടും സ്വാഗതം {row['Name']}.")
                    return row["UserID"], row["Name"]
        return user_session_manager()

def coached_scan(label):
    cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)
    cv2.namedWindow("PENSION-MITRA SCANNER", cv2.WINDOW_NORMAL)
    speak_native(f"നിങ്ങളുടെ {label} കാർഡ് കാണിക്കുക. ചിത്രം എടുക്കുന്നതിനായി എസ് അമർത്തുക.")
    while True:
        ret, frame = cap.read()
        if not ret: continue
        disp = frame.copy()
        cv2.rectangle(disp, (100, 100), (540, 380), (0, 255, 0), 2)
        cv2.putText(disp, f"Press 'S' for {label}", (110, 80), 1, 1.5, (0, 255, 0), 2)
        cv2.imshow("PENSION-MITRA SCANNER", disp)
        key = cv2.waitKey(1) & 0xFF
        if key in [ord('s'), ord('S')]:
            path = f"scan_{label.lower()}.jpg"; cv2.imwrite(path, frame)
            cap.release(); cv2.destroyAllWindows()
            return run_ocr(path, label.lower())
        elif key == 27: 
            cap.release(); cv2.destroyAllWindows()
            return DATASET.get(label.lower())

def run_ocr(path, doc_type):
    try:
        url = "https://api.sarvam.ai/extract"
        with open(path, 'rb') as f:
            res = requests.post(url, headers={"api-subscription-key": API_KEY}, 
                             files={'file': f}, data={'feature': 'document-digitization', 'language_code': 'en-IN'}, timeout=15)
        if res.status_code == 200:
            text = res.json().get('text', "").upper()
            if len(text) > 15: return text
    except: pass
    return DATASET.get(doc_type)

# --- 5. PLAYWRIGHT AUTOMATION ---

async def interactive_guide_automated(u_name, ppo_id, dob_val):
    abs_path = os.path.join(os.getcwd(), "mock_portal.html")
    local_path = "file:///" + abs_path.replace("\\", "/")
    
    steps = [
        ("രേഖകൾ കൃത്യമാണ്. നമുക്ക് മസ്റ്ററിംഗ് തുടങ്ങാം.", local_path),
        ("വിവരങ്ങൾ പൂരിപ്പിച്ചു. അടുത്ത ഘട്ടത്തിന് 'അടുത്തത്' എന്ന് പറയുക.", None), 
        ("ക്യാമറ റെഡിയാണ്. ദയവായി സ്ക്രീനിലേക്ക് നോക്കി ഒന്ന് കണ്ണുചിമ്മുക.", None),
        ("അഭിനന്ദനങ്ങൾ! നിങ്ങൾ വിജയകരമായി മസ്റ്ററിംഗ് പൂർത്തിയാക്കി.", None)
    ]

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        context = await browser.new_context(permissions=["camera"])
        page = await context.new_page()

        for i, (mal_text, url) in enumerate(steps):
            if url: await page.goto(url)
            
            # Step 1: Auto-Fill using evaluate to ensure completion
            if i == 1:
                await page.evaluate(f'document.getElementById("aadhaar_input").value = "XXXX-XXXX-9988"')
                await page.evaluate(f'document.getElementById("ppo_input").value = "{ppo_id}"')
                await page.evaluate(f'document.getElementById("dob_input").value = "{dob_val}"')

            # Step 2: Click Submit to start Scanning animation
            if i == 2: await page.click("#submit_btn") 

            # FINAL STEP: Exit cleanly
            if i == len(steps) - 1:
                speak_native(mal_text)
                print("--- SUCCESS: PROCESS COMPLETE ---")
                await asyncio.sleep(8); break 

            while True:
                speak_native(mal_text)
                cmd = listen_for_command()
                
                if any(x in cmd for x in ["അടുത്തത്", "aduthathu", "next", "ശരി"]): break
                elif any(x in cmd for x in ["വീണ്ടും", "veendum", "parayamo", "manasilayilla"]):
                    speak_native("ശരി, ഒന്നുകൂടി പറയാം."); continue
                elif any(x in cmd for x in ["നിർത്താം", "nirtham", "exit", "nirthikkoloo"]):
                    speak_native("മസ്റ്ററിംഗ് കഴിഞ്ഞിട്ടില്ല. നിർത്താൻ ഉറപ്പാണോ?")
                    conf = listen_for_command()
                    if any(x in conf for x in ["അതെ", "athe", "urappanu"]):
                        speak_native("മസ്റ്ററിംഗ് നിർത്തിയിരിക്കുന്നു."); await browser.close(); return
                    else: continue
        await browser.close()

# --- 6. MAIN CONTROLLER ---
async def main_async():
    if not API_KEY: print("API Key Missing!"); return
    u_id, u_name = user_session_manager()
    
    # 1. Capture Documents
    aad_text = coached_scan("Aadhaar")
    pen_text = coached_scan("Pension")

    # 2. Extract Data
    def get_val(pattern, text, default):
        match = re.search(pattern, text)
        return match.group(1).strip() if match else default

    # Extract Name, DOB, and Account Number
    a_name = get_val(r"NAME:\s*(.*?)(?=DOB|$)", aad_text, u_name).upper()
    p_name = get_val(r"NAME:\s*(.*?)(?=DOB|$)", pen_text, "RAGHAVAN MK").upper()
    
    a_dob = get_val(r"DOB:\s*(\d{2}/\d{2}/\d{4})", aad_text, "01/02/1960")
    p_dob = get_val(r"DOB:\s*(\d{2}/\d{2}/\d{4})", pen_text, "01/02/1960")

    # --- NEW: Extract Account Numbers ---
    a_acc = get_val(r"ACC:\s*(\d+)", aad_text, "00000000")
    p_acc = get_val(r"ACC:\s*(\d+)", pen_text, "11111111") # Example mismatch

    # 3. Detect Mismatches
    mismatches = []
    
    # Name Check
    if fuzz.ratio(a_name, p_name) < 90:
        mismatches.append(f"NAME (Aadhaar: {a_name} | Pension: {p_name})")
    
    # DOB Check
    if a_dob != p_dob:
        mismatches.append(f"DOB (Aadhaar: {a_dob} | Pension: {p_dob})")
    
    # --- NEW: Account Number Check ---
    if a_acc != p_acc:
        mismatches.append(f"BANK ACCOUNT (Aadhaar: {a_acc} | Pension: {p_acc})")

    # 4. Routing
    if not mismatches:
        print("✅ All data matches. Proceeding to Life Certificate...")
        await interactive_guide_automated(u_name, "88776655", a_dob)
    else:
        # If any of the 3 (Name, DOB, or ACC) fail, show the letter
        speak_native("ക്ഷമിക്കണം, രേഖകളിൽ ചില പൊരുത്തക്കേടുകൾ ഉണ്ട്. തിരുത്തൽ കത്ത് തയ്യാറാക്കിയിട്ടുണ്ട്.")
        show_correction_letter(u_name, "88776655", mismatches)

if __name__ == "__main__":
    asyncio.run(main_async())